# Generated by Django 3.2 on 2022-09-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('max_temp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('min_temp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('precipitation', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
