# Generated by Django 3.2 on 2022-09-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("avg_max_temp", models.FloatField(null=True)),
                ("avg_min_temp", models.FloatField(null=True)),
                ("total_precipitation", models.FloatField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="weatherdata",
            unique_together={("date", "max_temp", "min_temp", "precipitation")},
        ),
    ]
