# Generated by Django 3.2 on 2022-09-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20220905_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='max_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='min_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='precipitation',
            field=models.FloatField(),
        ),
    ]
