# Generated by Django 3.2 on 2022-09-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0005_alter_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherdata",
            name="max_temp",
            field=models.FloatField(
                default=-9999,
                help_text="Highest temperature recorded for the day (measured in degrees Celsius)",
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="min_temp",
            field=models.FloatField(
                default=-9999,
                help_text="Lowest temperature recorded for the day (measured in degrees Celsius)",
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="precipitation",
            field=models.FloatField(
                default=-9999,
                help_text="Amount of precipitation recorded for the day (measured in centimeters)",
            ),
        ),
    ]
