# Generated by Django 3.2 on 2022-09-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CropData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("corn_yield", models.IntegerField()),
            ],
            options={
                "unique_together": {("year", "corn_yield")},
            },
        ),
    ]
