# Generated by Django 3.2 on 2022-09-03 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cropdata',
            unique_together={('year', 'corn_yield')},
        ),
    ]
