# Generated by Django 3.2 on 2022-09-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_alter_cropdata_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cropdata',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cropdata',
            name='year',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
