# Generated by Django 3.2 on 2022-09-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0004_cropdata_unique_on_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropdata',
            name='corn_yield',
            field=models.IntegerField(help_text='Corn grain yield in the United States (measured in 1000s of megatons)'),
        ),
        migrations.AlterField(
            model_name='cropdata',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Year of the harvest', unique=True),
        ),
    ]
